# Generated by Django 4.2 on 2023-04-14 11:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Muqova rasm')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqti')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
