# Generated by Django 4.2 on 2023-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='       ', max_length=255),
            preserve_default=False,
        ),
    ]
