# Generated by Django 4.2 on 2023-04-16 13:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_cafedra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafedra',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
