# Generated by Django 4.2 on 2023-04-17 06:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_fakultet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultet',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='image',
            field=models.ImageField(default=' ', upload_to='fakultet/', verbose_name='rasmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakultet',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
