# Generated by Django 4.2 on 2023-04-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafedra',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'Markaz', 'verbose_name_plural': 'Markazlar'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='fakultet',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': 'Fakultetlar'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
