# Generated by Django 4.2 on 2023-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0014_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=' ', max_length=50, verbose_name='nomi'),
            preserve_default=False,
        ),
    ]
