# Generated by Django 4.2 on 2023-04-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0016_remove_category_content_remove_category_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='df', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.category'),
        ),
    ]
