# Generated by Django 4.2 on 2023-04-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0017_page_slug_alter_page_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.OneToOneField(blank=True, help_text='Sahifa tanlang.Majburiy emas', null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.page', verbose_name='Sahifa'),
        ),
    ]
