# Generated by Django 4.2 on 2023-04-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0018_remove_category_slug_remove_page_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.URLField(blank=True, default=False, help_text='Boshqa sayt uchun link.Majburiy emas', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Nomi'),
        ),
    ]
