# Generated by Django 4.2 on 2023-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0019_category_link_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.URLField(blank=True, help_text='Boshqa sayt uchun link.Majburiy emas', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text="Agar bosh kategoriya bo'lsa majburiy emas", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='institute.category'),
        ),
    ]
