# Generated by Django 4.2 on 2023-04-25 04:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("institute", "0021_alter_page_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Menyu", "verbose_name_plural": "Menyu"},
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
