# Generated by Django 4.2 on 2023-04-25 04:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institute", "0022_alter_category_options_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
